### PR TITLE
refactor: create and implement generate-grid mixin

### PR DESCRIPTION
**Pull request by adonyssantos**

### CODE REVIEW

**Review by 0s1n — CHANGES_REQUESTED** [review]
It's not working
imagen

**Comment by adonyssantos** [comment]
> It's not working imagen

@0s1n fixed. Check again

**Review by 0s1n — CHANGES_REQUESTED** [review]
Still not working.
imagen

**Comment by adonyssantos** [comment]
> Still not working. imagen

@0s1n Fixed again. There is a error with the grid responsive but we can work this in another issue. 

The problem is that it should show 4 columns on the desktop:  
image

Also, we need to check the horizontal spacing on mobile:
image

**Review by 0s1n — APPROVED** [review]

**Pull request merged**
